export const qualificationCopy = {
  en: {
    title: 'Tutor certificates',
    intro: 'Add certificates or education documents for private verification.',
    multipleHint: 'You can add multiple documents, one at a time.',
    documentListTitle: 'Submitted documents',
    uploadTitle: 'Submit a document',
    chooseFile: 'Choose a certificate file',
    selectedFile: 'Selected file',
    removeSelection: 'Remove selected file',
    typeLabel: 'Document type',
    types: { DEGREE: 'Degree', CERTIFICATE: 'Certificate' },
    fileLabel: 'PDF, JPEG or PNG, up to 5 MB',
    selectFile: 'Choose a document before submitting.',
    upload: 'Submit document',
    uploading: 'Uploading document',
    saving: 'Saving review',
    refresh: 'Refresh documents',
    refreshing: 'Refreshing documents…',
    refreshSuccess: 'Documents are up to date.',
    profileRefreshError: 'Documents refreshed, but profile status could not be updated.',
    empty: 'No documents submitted yet.',
    loading: 'Loading documents…',
    loadError: 'Could not load documents. Try again.',
    uploadSuccess: 'Document submitted for review.',
    uploadError: 'Could not submit the document. Check its file type and try again.',
    uploadUncertain:
      'Could not confirm the upload. Check the latest documents before submitting again.',
    uploadConflict: 'A document of this type is already pending. The list has been refreshed.',
    pendingType: 'A document of this type is already pending review.',
    fileErrors: {
      empty: 'Choose a file that is not empty.',
      type: 'Choose a PDF, JPEG or PNG file.',
      size: 'The file must be 5 MB or smaller.',
    },
    status: { PENDING: 'Pending review', APPROVED: 'Approved', REJECTED: 'Rejected' },
    reviewedAt: 'Reviewed',
    submittedAt: 'Submitted',
    rejectionReason: 'Review note',
    preview: 'View document',
    previewLoading: 'Requesting a private preview…',
    previewReady: 'Open private document',
    previewExpiry: 'Link expires',
    previewExpired: 'This preview link has expired. Request a new one.',
    previewDenied: 'Preview access was denied. Refresh the list and try again.',
    previewMissing: 'This document is no longer available. Refresh the list.',
    previewError: 'Could not create a preview link. Try again.',
    previewRetry: 'Request a new link',
    previewHelp: 'If the link opens an expired or denied page, request a new link here.',
    queueTitle: 'Tutor verification queue',
    queueIntro: 'Review private evidence before updating a tutor’s verification status.',
    queueEmpty: 'No documents in this view.',
    queueError: 'Could not load the queue. Try again.',
    loadMore: 'Load more',
    selectDocument: 'Select a document to review its details.',
    detailsError: 'Could not load document details. Select it again or refresh the queue.',
    reviewHistory: 'Review history',
    reviewTitle: 'Review decision',
    approve: 'Approve',
    reject: 'Reject',
    noteLabel: 'Review note',
    noteOptional: 'Optional for approval; required for rejection (up to 500 characters).',
    noteRequired: 'Enter a reason before rejecting.',
    noteTooLong: 'The note must be 500 characters or fewer.',
    reviewSuccess: 'Review saved.',
    reviewError: 'Could not confirm the review. Check its current status before trying again.',
    reviewConflict: 'This document was reviewed elsewhere. The queue has been refreshed.',
    denied: 'You do not have access to this verification view.',
    unavailable: 'The service is unavailable. Try again.',
    unknownType: 'Other document',
  },
  th: {
    title: 'เอกสารรับรองติวเตอร์',
    intro: 'เพิ่มใบรับรองหรือเอกสารการศึกษาเพื่อให้ผู้ดูแลตรวจสอบเป็นการส่วนตัว',
    multipleHint: 'เพิ่มเอกสารได้หลายรายการ โดยส่งครั้งละหนึ่งไฟล์',
    documentListTitle: 'เอกสารที่ส่งแล้ว',
    uploadTitle: 'ส่งเอกสาร',
    chooseFile: 'เลือกไฟล์เอกสารรับรอง',
    selectedFile: 'ไฟล์ที่เลือก',
    removeSelection: 'ลบไฟล์ที่เลือก',
    typeLabel: 'ประเภทเอกสาร',
    types: { DEGREE: 'วุฒิการศึกษา', CERTIFICATE: 'ประกาศนียบัตร' },
    fileLabel: 'PDF, JPEG หรือ PNG ขนาดไม่เกิน 5 MB',
    selectFile: 'เลือกเอกสารก่อนส่ง',
    upload: 'ส่งเอกสาร',
    uploading: 'กำลังอัปโหลดเอกสาร',
    saving: 'กำลังบันทึกผลตรวจ',
    refresh: 'โหลดรายการใหม่',
    refreshing: 'กำลังโหลดรายการเอกสารใหม่…',
    refreshSuccess: 'รายการเอกสารเป็นข้อมูลล่าสุดแล้ว',
    profileRefreshError: 'โหลดรายการเอกสารใหม่แล้ว แต่ปรับสถานะโปรไฟล์ไม่ได้',
    empty: 'ยังไม่มีเอกสารที่ส่ง',
    loading: 'กำลังโหลดเอกสาร…',
    loadError: 'โหลดเอกสารไม่ได้ โปรดลองอีกครั้ง',
    uploadSuccess: 'ส่งเอกสารเพื่อตรวจสอบแล้ว',
    uploadError: 'ส่งเอกสารไม่ได้ ตรวจสอบชนิดไฟล์แล้วลองอีกครั้ง',
    uploadUncertain: 'ยืนยันผลการส่งเอกสารไม่ได้ โปรดตรวจสอบรายการล่าสุดก่อนส่งอีกครั้ง',
    uploadConflict: 'มีเอกสารประเภทนี้รอตรวจอยู่แล้ว ระบบโหลดรายการใหม่แล้ว',
    pendingType: 'มีเอกสารประเภทนี้รอตรวจอยู่แล้ว',
    fileErrors: {
      empty: 'เลือกไฟล์ที่ไม่ว่างเปล่า',
      type: 'เลือกไฟล์ PDF, JPEG หรือ PNG',
      size: 'ไฟล์ต้องมีขนาดไม่เกิน 5 MB',
    },
    status: { PENDING: 'รอตรวจสอบ', APPROVED: 'อนุมัติแล้ว', REJECTED: 'ไม่ผ่าน' },
    reviewedAt: 'ตรวจเมื่อ',
    submittedAt: 'ส่งเมื่อ',
    rejectionReason: 'หมายเหตุการตรวจ',
    preview: 'ดูเอกสาร',
    previewLoading: 'กำลังขอลิงก์ส่วนตัว…',
    previewReady: 'เปิดเอกสารส่วนตัว',
    previewExpiry: 'ลิงก์หมดอายุ',
    previewExpired: 'ลิงก์ดูเอกสารหมดอายุแล้ว ขอใหม่ได้',
    previewDenied: 'ไม่มีสิทธิ์ดูเอกสาร โหลดรายการใหม่แล้วลองอีกครั้ง',
    previewMissing: 'ไม่พบเอกสารนี้แล้ว โหลดรายการใหม่',
    previewError: 'ขอลิงก์ดูเอกสารไม่ได้ โปรดลองอีกครั้ง',
    previewRetry: 'ขอลิงก์ใหม่',
    previewHelp: 'ถ้าลิงก์เปิดแล้วแจ้งว่าหมดอายุหรือถูกปฏิเสธ ให้ขอลิงก์ใหม่ที่นี่',
    queueTitle: 'คิวตรวจคุณสมบัติติวเตอร์',
    queueIntro: 'ตรวจหลักฐานส่วนตัวก่อนเปลี่ยนสถานะการยืนยันติวเตอร์',
    queueEmpty: 'ไม่มีเอกสารในรายการนี้',
    queueError: 'โหลดคิวตรวจไม่ได้ โปรดลองอีกครั้ง',
    loadMore: 'โหลดเพิ่มเติม',
    selectDocument: 'เลือกเอกสารเพื่อดูรายละเอียดและตรวจสอบ',
    detailsError: 'โหลดรายละเอียดเอกสารไม่ได้ เลือกเอกสารอีกครั้งหรือโหลดคิวใหม่',
    reviewHistory: 'ประวัติการตรวจ',
    reviewTitle: 'ผลการตรวจ',
    approve: 'อนุมัติ',
    reject: 'ไม่ผ่าน',
    noteLabel: 'หมายเหตุการตรวจ',
    noteOptional: 'อนุมัติไม่จำเป็นต้องระบุ แต่ไม่ผ่านต้องระบุ (ไม่เกิน 500 ตัวอักษร)',
    noteRequired: 'ระบุเหตุผลก่อนเลือกไม่ผ่าน',
    noteTooLong: 'หมายเหตุต้องไม่เกิน 500 ตัวอักษร',
    reviewSuccess: 'บันทึกผลตรวจแล้ว',
    reviewError: 'ยืนยันผลการตรวจไม่ได้ โปรดตรวจสอบสถานะล่าสุดก่อนลองอีกครั้ง',
    reviewConflict: 'เอกสารนี้ถูกตรวจจากที่อื่นแล้ว ระบบโหลดคิวใหม่แล้ว',
    denied: 'คุณไม่มีสิทธิ์เข้าถึงหน้าตรวจคุณสมบัตินี้',
    unavailable: 'บริการไม่พร้อมใช้งาน โปรดลองอีกครั้ง',
    unknownType: 'เอกสารอื่น',
  },
} as const;

export type QualificationCopy = (typeof qualificationCopy)['en'] | (typeof qualificationCopy)['th'];
