export const conversationCopy = {
  en: {
    title: 'Your messages',
    eyebrow: 'Before your lesson',
    hint: 'Ask about learning goals and lessons. No booking is required.',
    inbox: 'Conversations',
    history: 'Conversation history',
    openLink: 'Open link in a new tab',
    back: 'Back to conversations',
    tutor: 'Tutor',
    student: 'Student',
    ask: 'Ask the tutor',
    pick: 'Choose a conversation',
    pickHint: 'Your messages stay between you and the other participant.',
    empty: 'Your next conversation starts here',
    studentEmpty: 'Open a tutor profile and choose “Ask the tutor”.',
    tutorEmpty: 'Conversations appear here when a student contacts you.',
    browse: 'Find a tutor',
    noMessages: 'Say hello. What would you like to learn?',
    noPreview: 'Start a conversation',
    loading: 'Loading messages…',
    more: 'More conversations',
    refresh: 'Refresh',
    refreshInbox: 'Refresh conversations',
    refreshThread: 'Refresh messages',
    refreshing: 'Refreshing…',
    retry: 'Try again',
    draft: 'Temporary draft',
    draftLimit: '2,000 characters max. Draft clears if you leave or reload this page.',
    compose: 'Your message',
    placeholder: 'Write a message…',
    limit: 'Up to 2,000 characters. New lines are allowed.',
    tooLong: 'Please shorten your message to 2,000 characters.',
    send: 'Send',
    sendLabel: 'Send',
    sending: 'Sending…',
    sent: 'Message sent',
    sendFailed:
      'Could not confirm sending. Refresh messages and check the conversation before sending again. Your draft stays on this page; leaving or reloading clears it.',
    failed: 'Could not load messages. Please try again.',
    historyTimeout: 'Loading messages took too long. Please try again.',
    historyLimit:
      'Stopped loading to avoid too many requests. History is incomplete. Please try again.',
    expired: 'Your session has expired. Please sign in again.',
    forbidden: 'You do not have access to this conversation.',
    missing: 'This conversation or tutor is no longer available.',
    signIn: 'Sign in',
    latest: 'Back to latest messages',
    newMessages: '{count} new messages',
    unread: '{count} unread messages',
    profileError: 'Could not verify your profile. Reload to try again.',
    reload: 'Reload page',
    manual: 'Refresh to see new messages.',
  },
  th: {
    title: 'ข้อความของคุณ',
    eyebrow: 'คุยกันก่อนเริ่มเรียน',
    hint: 'สอบถามเป้าหมายและรายละเอียดการเรียนได้ โดยยังไม่ต้องจอง',
    inbox: 'บทสนทนา',
    history: 'ประวัติข้อความ',
    openLink: 'เปิดลิงก์ในแท็บใหม่',
    back: 'กลับรายชื่อบทสนทนา',
    tutor: 'ติวเตอร์',
    student: 'นักเรียน',
    ask: 'สอบถามติวเตอร์',
    pick: 'เลือกบทสนทนา',
    pickHint: 'ข้อความนี้เป็นส่วนตัวระหว่างคุณกับคู่สนทนา',
    empty: 'เริ่มบทสนทนาแรกของคุณ',
    studentEmpty: 'เปิดโปรไฟล์ติวเตอร์ แล้วเลือก “สอบถามติวเตอร์”',
    tutorEmpty: 'บทสนทนาจะปรากฏที่นี่เมื่อนักเรียนติดต่อคุณ',
    browse: 'ค้นหาติวเตอร์',
    noMessages: 'ทักทายกันก่อน อยากเรียนรู้เรื่องอะไรบ้าง?',
    noPreview: 'เริ่มบทสนทนา',
    loading: 'กำลังโหลดข้อความ…',
    more: 'บทสนทนาเพิ่มเติม',
    refresh: 'รีเฟรช',
    refreshInbox: 'รีเฟรชรายชื่อ',
    refreshThread: 'รีเฟรชข้อความ',
    refreshing: 'กำลังรีเฟรช…',
    retry: 'ลองอีกครั้ง',
    draft: 'ร่างชั่วคราว',
    draftLimit: 'ไม่เกิน 2,000 ตัวอักษร ร่างหายเมื่อออกจากหน้านี้หรือโหลดใหม่',
    compose: 'ข้อความของคุณ',
    placeholder: 'พิมพ์ข้อความ…',
    limit: 'ไม่เกิน 2,000 ตัวอักษร ขึ้นบรรทัดใหม่ได้',
    tooLong: 'กรุณาลดข้อความให้ไม่เกิน 2,000 ตัวอักษร',
    send: 'ส่งข้อความ',
    sendLabel: 'ส่ง',
    sending: 'กำลังส่ง…',
    sent: 'ส่งข้อความแล้ว',
    sendFailed:
      'ยังยืนยันการส่งไม่ได้ กรุณารีเฟรชข้อความและตรวจสอบก่อนส่งซ้ำ ร่างยังอยู่ในหน้านี้ แต่จะหายเมื่อออกจากหน้าหรือโหลดใหม่',
    failed: 'โหลดข้อความไม่สำเร็จ กรุณาลองอีกครั้ง',
    historyTimeout: 'โหลดข้อความนานเกินไป กรุณาลองอีกครั้ง',
    historyLimit: 'หยุดโหลดเพื่อป้องกันคำขอจำนวนมาก ประวัติยังโหลดไม่ครบ กรุณาลองอีกครั้ง',
    expired: 'เซสชันหมดอายุ กรุณาเข้าสู่ระบบอีกครั้ง',
    forbidden: 'คุณไม่มีสิทธิ์เข้าถึงบทสนทนานี้',
    missing: 'ไม่พบบทสนทนาหรือติวเตอร์นี้แล้ว',
    signIn: 'เข้าสู่ระบบ',
    latest: 'กลับข้อความล่าสุด',
    newMessages: 'ข้อความใหม่ {count}',
    unread: 'ข้อความที่ยังไม่อ่าน {count}',
    profileError: 'ตรวจสอบโปรไฟล์ไม่สำเร็จ กรุณาโหลดหน้าใหม่เพื่อลองอีกครั้ง',
    reload: 'โหลดหน้าใหม่',
    manual: 'รีเฟรชเพื่อดูข้อความใหม่',
  },
} as const;

export type ConversationCopy = (typeof conversationCopy)['en' | 'th'];
