export const conversationCopy = {
  en: {
    title: 'A little conversation, before your lesson',
    eyebrow: 'Messages',
    hint: 'Ask about learning goals and lessons. No booking is required.',
    inbox: 'Your conversations',
    history: 'Conversation history',
    back: 'Back to conversations',
    tutor: 'Tutor',
    student: 'Student',
    ask: 'Ask the tutor',
    pick: 'Choose a conversation',
    pickHint: 'Your messages stay between you and the other participant.',
    empty: 'Your next conversation starts here',
    studentEmpty: 'Open a tutor profile and choose “Ask the tutor”.',
    tutorEmpty: 'Conversations appear here when a student contacts you.',
    browse: 'Find a tutor',
    noMessages: 'Say hello. What would you like to learn?',
    noPreview: 'Start a conversation',
    loading: 'Loading messages…',
    more: 'More conversations',
    refresh: 'Refresh',
    refreshing: 'Refreshing…',
    retry: 'Try again',
    draft: 'Draft kept',
    compose: 'Your message',
    placeholder: 'Write a message…',
    limit: 'Up to 2,000 characters. New lines are allowed.',
    tooLong: 'Please shorten your message to 2,000 characters.',
    send: 'Send',
    sending: 'Sending…',
    sent: 'Message sent',
    sendFailed:
      'Could not confirm sending. Your draft is kept. Refresh and check the conversation before sending again.',
    failed: 'Could not load messages. Please try again.',
    expired: 'Your session has expired. Please sign in again.',
    forbidden: 'You do not have access to this conversation.',
    missing: 'This conversation or tutor is no longer available.',
    signIn: 'Sign in',
    latest: 'Back to latest messages',
    newMessages: '{count} new messages',
    unread: '{count} unread messages',
    profileError: 'Could not verify your profile. Reload to try again.',
    reload: 'Reload page',
    manual: 'Use Refresh to check for new messages.',
  },
  th: {
    title: 'คุยกันสักนิด ก่อนเริ่มเรียน',
    eyebrow: 'ข้อความ',
    hint: 'สอบถามเป้าหมายและรายละเอียดการเรียนได้ โดยยังไม่ต้องจอง',
    inbox: 'บทสนทนาของคุณ',
    history: 'ประวัติข้อความ',
    back: 'กลับรายชื่อบทสนทนา',
    tutor: 'ติวเตอร์',
    student: 'นักเรียน',
    ask: 'สอบถามติวเตอร์',
    pick: 'เลือกบทสนทนา',
    pickHint: 'ข้อความนี้เป็นส่วนตัวระหว่างคุณกับคู่สนทนา',
    empty: 'เริ่มบทสนทนาแรกของคุณ',
    studentEmpty: 'เปิดโปรไฟล์ติวเตอร์ แล้วเลือก “สอบถามติวเตอร์”',
    tutorEmpty: 'บทสนทนาจะปรากฏที่นี่เมื่อนักเรียนติดต่อคุณ',
    browse: 'ค้นหาติวเตอร์',
    noMessages: 'ทักทายกันก่อน อยากเรียนรู้เรื่องอะไรบ้าง?',
    noPreview: 'เริ่มบทสนทนา',
    loading: 'กำลังโหลดข้อความ…',
    more: 'บทสนทนาเพิ่มเติม',
    refresh: 'รีเฟรช',
    refreshing: 'กำลังรีเฟรช…',
    retry: 'ลองอีกครั้ง',
    draft: 'เก็บร่างไว้แล้ว',
    compose: 'ข้อความของคุณ',
    placeholder: 'พิมพ์ข้อความ…',
    limit: 'ไม่เกิน 2,000 ตัวอักษร ขึ้นบรรทัดใหม่ได้',
    tooLong: 'กรุณาลดข้อความให้ไม่เกิน 2,000 ตัวอักษร',
    send: 'ส่งข้อความ',
    sending: 'กำลังส่ง…',
    sent: 'ส่งข้อความแล้ว',
    sendFailed: 'ยังยืนยันการส่งไม่ได้ เก็บร่างไว้แล้ว กรุณารีเฟรชและตรวจสอบบทสนทนาก่อนส่งซ้ำ',
    failed: 'โหลดข้อความไม่สำเร็จ กรุณาลองอีกครั้ง',
    expired: 'เซสชันหมดอายุ กรุณาเข้าสู่ระบบอีกครั้ง',
    forbidden: 'คุณไม่มีสิทธิ์เข้าถึงบทสนทนานี้',
    missing: 'ไม่พบบทสนทนาหรือติวเตอร์นี้แล้ว',
    signIn: 'เข้าสู่ระบบ',
    latest: 'กลับข้อความล่าสุด',
    newMessages: 'ข้อความใหม่ {count}',
    unread: 'ข้อความที่ยังไม่อ่าน {count}',
    profileError: 'ตรวจสอบโปรไฟล์ไม่สำเร็จ กรุณาโหลดหน้าใหม่เพื่อลองอีกครั้ง',
    reload: 'โหลดหน้าใหม่',
    manual: 'กดรีเฟรชเพื่อตรวจสอบข้อความใหม่',
  },
} as const;

export type ConversationCopy = (typeof conversationCopy)['en' | 'th'];
