export const tutorBookingInboxCopy = {
  en: {
    eyebrow: 'Incoming bookings',
    title: 'Booking inbox',
    subtitle: 'Review requests for your listings, then confirm or reject.',
    count: '{count} bookings · {status}',
    countUnavailable: 'Booking count unavailable',
    filterLabel: 'Filter bookings by status',
    all: 'All',
    loading: 'Loading your booking inbox…',
    loadError: 'We could not load your booking inbox right now.',
    tryAgain: 'Try again',
    refresh: 'Refresh',
    emptyTitle: 'No booking requests yet',
    emptyBody:
      'Publish a teaching listing and open availability so students can send their first request.',
    emptyFilterTitle: 'No bookings in this view',
    emptyFilterBody: 'Choose another status to see the rest of your bookings.',
    manageAvailability: 'Manage availability',
    myListings: 'My listings',
    unknownStudent: 'Student unavailable',
    lessonTime: 'Lesson time',
    bangkokTime: 'Bangkok time (UTC+7)',
    amount: 'You earn',
    confirmAction: 'Confirm',
    rejectAction: 'Reject',
    confirmFor: 'Confirm the booking from {student}',
    rejectFor: 'Reject the booking from {student}',
    working: 'Working…',
    decidedHint: 'No reply needed. Only a pending request can be confirmed or rejected.',
    confirmTitle: 'Confirm this booking?',
    confirmBody: 'The student keeps this time and the slot stays reserved.',
    confirmSubmit: 'Yes, confirm booking',
    rejectTitle: 'Reject this booking?',
    rejectBody:
      'The booking is canceled and the time opens again for other students. Tell the student why.',
    rejectSubmit: 'Yes, reject booking',
    reasonLabel: 'Reason (optional)',
    reasonPlaceholder: 'I am no longer available at that time.',
    textHint: 'Up to {max} characters.',
    textTooLong: 'Use {max} characters or fewer.',
    cancel: 'Keep as pending',
    confirmSuccess: 'Booking confirmed. The lesson time stays reserved.',
    rejectSuccessSlotOpen: 'Booking rejected. The lesson time is open again.',
    rejectSuccessSlotHeld: 'Booking rejected. Another active booking still holds that time.',
    staleStatusError:
      'This request is no longer pending. Refresh the inbox to see its current status.',
    staleRaceError: 'Another update changed this booking first. Refresh the inbox and try again.',
    ownershipError: 'This booking belongs to another tutor. Nothing was changed.',
    missingError: 'This booking no longer exists. Refresh the inbox.',
    validationError: 'Please check the reason and try again.',
    authError: 'Your session has expired. Please sign in again to continue.',
    unknownError: 'Something went wrong and nothing was changed. Please try again.',
    pagination: 'Booking inbox pages',
    previousPage: 'Previous',
    nextPage: 'Next',
    pageOf: 'Page {page} of {totalPages}',
  },
  th: {
    eyebrow: 'การจองที่เข้ามา',
    title: 'กล่องคำขอจอง',
    subtitle: 'ตรวจคำขอจองในคอร์สของคุณ แล้วยืนยันหรือปฏิเสธ',
    count: '{count} รายการ · {status}',
    countUnavailable: 'ยังไม่ทราบจำนวนรายการจอง',
    filterLabel: 'กรองการจองตามสถานะ',
    all: 'ทั้งหมด',
    loading: 'กำลังโหลดกล่องคำขอจอง…',
    loadError: 'ไม่สามารถโหลดกล่องคำขอจองได้ในขณะนี้',
    tryAgain: 'ลองอีกครั้ง',
    refresh: 'รีเฟรช',
    emptyTitle: 'ยังไม่มีคำขอจอง',
    emptyBody: 'เผยแพร่ประกาศสอนและเปิดเวลาว่าง เพื่อให้นักเรียนส่งคำขอจองแรกเข้ามาได้',
    emptyFilterTitle: 'ไม่มีการจองในมุมมองนี้',
    emptyFilterBody: 'เลือกสถานะอื่นเพื่อดูการจองที่เหลือ',
    manageAvailability: 'จัดการตารางว่าง',
    myListings: 'คอร์สของฉัน',
    unknownStudent: 'ไม่พบข้อมูลนักเรียน',
    lessonTime: 'เวลาเรียน',
    bangkokTime: 'เวลากรุงเทพฯ (UTC+7)',
    amount: 'รายได้ของคุณ',
    confirmAction: 'ยืนยัน',
    rejectAction: 'ปฏิเสธ',
    confirmFor: 'ยืนยันการจองจาก {student}',
    rejectFor: 'ปฏิเสธการจองจาก {student}',
    working: 'กำลังดำเนินการ…',
    decidedHint: 'ไม่ต้องตอบกลับ ยืนยันหรือปฏิเสธได้เฉพาะคำขอที่ยังรอดำเนินการ',
    confirmTitle: 'ยืนยันการจองนี้?',
    confirmBody: 'นักเรียนจะได้เวลานี้และระบบจะกันเวลาไว้ต่อ',
    confirmSubmit: 'ยืนยันการจอง',
    rejectTitle: 'ปฏิเสธการจองนี้?',
    rejectBody:
      'การจองจะถูกยกเลิกและเวลานี้จะเปิดให้นักเรียนคนอื่นจองได้ โปรดแจ้งเหตุผลให้นักเรียนทราบ',
    rejectSubmit: 'ปฏิเสธการจอง',
    reasonLabel: 'เหตุผล (ไม่บังคับ)',
    reasonPlaceholder: 'ช่วงเวลานั้นผมไม่ว่างแล้ว',
    textHint: 'พิมพ์ได้ไม่เกิน {max} ตัวอักษร',
    textTooLong: 'กรุณาพิมพ์ไม่เกิน {max} ตัวอักษร',
    cancel: 'คงสถานะรอดำเนินการ',
    confirmSuccess: 'ยืนยันการจองแล้ว ระบบยังกันเวลาเรียนนี้ไว้',
    rejectSuccessSlotOpen: 'ปฏิเสธการจองแล้ว เวลานี้กลับมาว่างอีกครั้ง',
    rejectSuccessSlotHeld: 'ปฏิเสธการจองแล้ว แต่ยังมีการจองอื่นที่ใช้เวลานี้อยู่',
    staleStatusError: 'คำขอนี้ไม่ได้รอดำเนินการแล้ว กรุณารีเฟรชเพื่อดูสถานะล่าสุด',
    staleRaceError: 'มีการอัปเดตการจองนี้ก่อนหน้าคุณ กรุณารีเฟรชแล้วลองอีกครั้ง',
    ownershipError: 'การจองนี้เป็นของติวเตอร์คนอื่น ระบบไม่ได้เปลี่ยนแปลงข้อมูล',
    missingError: 'ไม่พบการจองนี้แล้ว กรุณารีเฟรชกล่องคำขอจอง',
    validationError: 'กรุณาตรวจสอบเหตุผลแล้วลองอีกครั้ง',
    authError: 'เซสชันหมดอายุแล้ว กรุณาเข้าสู่ระบบอีกครั้ง',
    unknownError: 'เกิดข้อผิดพลาดและระบบไม่ได้เปลี่ยนแปลงข้อมูล กรุณาลองอีกครั้ง',
    pagination: 'หน้าของกล่องคำขอจอง',
    previousPage: 'ก่อนหน้า',
    nextPage: 'ถัดไป',
    pageOf: 'หน้า {page} จาก {totalPages}',
  },
} as const;

export type TutorBookingInboxCopy = {
  [Key in keyof (typeof tutorBookingInboxCopy)['en']]: string;
};
