export const publicTutorDetailCopy = {
  en: {
    title: 'Meet your tutor. Find your time.',
    tutor: 'Tutor',
    about: 'About me',
    experience: 'Teaching experience',
    years: 'years',
    selected: 'Selected course',
    select: 'Choose this course',
    selectedButton: 'Selected',
    courses: 'courses',
    page: 'Page',
    coursePages: 'Course pages',
    coursePagesHint: 'Drag or scroll to change page. Use arrow keys, Home or End when focused.',
    coursePageStatus: 'Page {page} of {pages} · Courses {range} of {total}',
    selectedCoursePage: 'The selected course is on page {page}.',
    returnToCourse: 'Back to selected course',
    noListings: 'No published courses are available right now.',
    selectFirst: 'Choose a course before selecting a time.',
    hour: 'hour',
    appointmentPad: 'Appointment pad',
    allDates: 'All dates',
    dateIndex: 'Dates with available times',
    window: 'Times within the next 30 days',
    availabilityNote: 'These tutor times apply to the course selected above.',
    continueHint: 'Choose a time to review your booking request.',
    showing: 'Showing {count} available times · {date}',
  },
  th: {
    title: 'รู้จักติวเตอร์ เลือกเวลาเรียน',
    tutor: 'ติวเตอร์',
    about: 'เกี่ยวกับฉัน',
    experience: 'ประสบการณ์สอน',
    years: 'ปี',
    selected: 'กำลังเลือก',
    select: 'เลือกคอร์สนี้',
    selectedButton: 'เลือกอยู่',
    courses: 'คอร์ส',
    page: 'หน้า',
    coursePages: 'หน้ารายการคอร์ส',
    coursePagesHint: 'ลากหรือเลื่อนเพื่อเปลี่ยนหน้า ใช้ปุ่มลูกศร Home หรือ End เมื่อโฟกัสอยู่',
    coursePageStatus: 'หน้า {page} จาก {pages} · คอร์ส {range} จาก {total}',
    selectedCoursePage: 'คอร์สที่เลือกอยู่หน้า {page}',
    returnToCourse: 'กลับไปคอร์สที่เลือก',
    noListings: 'ยังไม่มีคอร์สที่เปิดสอน',
    selectFirst: 'เลือกคอร์สก่อนเลือกเวลา',
    hour: 'ชั่วโมง',
    appointmentPad: 'สมุดนัดเรียน',
    allDates: 'ทุกวัน',
    dateIndex: 'วันที่มีเวลาว่าง',
    window: 'เวลาว่างภายใน 30 วันข้างหน้า',
    availabilityNote: 'เวลาว่างของติวเตอร์ใช้กับคอร์สที่กำลังเลือกด้านบน',
    continueHint: 'เลือกเวลาเพื่อไปตรวจสอบคำขอเรียน',
    showing: 'แสดง {count} ช่วงเวลาว่าง · {date}',
  },
} as const;
