export const tutorSearchCopy = {
  en: {
    eyebrow: 'Tutor search',
    title: 'Find an exact match',
    subtitle:
      'Filter published listings from verified tutors by subject, grade, maximum budget and minimum rating.',
    student: 'Student',
    filters: 'Filters',
    filtersHint: 'All selected filters are combined.',
    subject: 'Subject',
    allSubjects: 'All subjects',
    grade: 'Grade level',
    allGrades: 'All grades',
    maxPrice: 'Maximum budget (THB/hour)',
    maxPriceHint: 'The upper limit is inclusive.',
    minimumRating: 'Minimum rating',
    anyRating: 'Any rating',
    ratingHint: 'Tutors without a rating are excluded when a minimum is selected.',
    apply: 'Apply filters',
    clear: 'Clear',
    clearAllFilters: 'Clear all filters',
    exactMatches: 'exact matches',
    anySubject: 'Any subject',
    anyGrade: 'Any grade',
    anyBudget: 'Any budget',
    upTo: 'up to',
    ratingSummary: 'rating',
    verifiedOnly: 'VERIFIED TUTORS ONLY',
    verified: 'VERIFIED',
    loading: 'Loading tutors…',
    loadingCatalog: 'Loading subjects and grade levels…',
    catalogError: 'Subject and grade options are temporarily unavailable.',
    searchError: 'We could not load tutors right now. Please try again.',
    validationError: 'Please check the highlighted filters.',
    noMatches: 'No exact matches found',
    noMatchesHint: 'Try clearing one or more filters to see other published Tutors.',
    years: 'years experience',
    newTutor: 'New tutor',
    reviews: 'reviews',
    noFutureSlots: 'No future slots',
    next: 'Next',
    hour: 'hour',
    viewTimes: 'View times',
    cardNote:
      "Each card represents one matching teaching listing. Prices and subjects are never mixed across a tutor's other listings.",
  },
  th: {
    eyebrow: 'ค้นหาติวเตอร์',
    title: 'ค้นหาติวเตอร์ที่ตรงกับคุณ',
    subtitle:
      'กรองคอร์สที่เผยแพร่จากติวเตอร์ที่ผ่านการยืนยันแล้ว ตามวิชา ระดับชั้น งบสูงสุด และคะแนนขั้นต่ำ',
    student: 'นักเรียน',
    filters: 'ตัวกรอง',
    filtersHint: 'ระบบจะใช้ตัวกรองที่เลือกทั้งหมดร่วมกัน',
    subject: 'วิชา',
    allSubjects: 'ทุกวิชา',
    grade: 'ระดับชั้น',
    allGrades: 'ทุกระดับชั้น',
    maxPrice: 'ราคาสูงสุด (บาท/ชั่วโมง)',
    maxPriceHint: 'ราคาที่เท่ากับค่าสูงสุดจะแสดงด้วย',
    minimumRating: 'คะแนนขั้นต่ำ',
    anyRating: 'ทุกคะแนน',
    ratingHint: 'ติวเตอร์ที่ยังไม่มีคะแนนจะไม่แสดงเมื่อเลือกคะแนนขั้นต่ำ',
    apply: 'ใช้ตัวกรอง',
    clear: 'ล้าง',
    clearAllFilters: 'ล้างตัวกรองทั้งหมด',
    exactMatches: 'ผลลัพธ์ที่ตรงกัน',
    anySubject: 'ทุกวิชา',
    anyGrade: 'ทุกระดับชั้น',
    anyBudget: 'ไม่จำกัดงบ',
    upTo: 'ไม่เกิน',
    ratingSummary: 'คะแนน',
    verifiedOnly: 'เฉพาะติวเตอร์ที่ยืนยันแล้ว',
    verified: 'ยืนยันแล้ว',
    loading: 'กำลังโหลดข้อมูลติวเตอร์…',
    loadingCatalog: 'กำลังโหลดวิชาและระดับชั้น…',
    catalogError: 'ไม่สามารถโหลดตัวเลือกวิชาและระดับชั้นได้ชั่วคราว',
    searchError: 'ไม่สามารถโหลดข้อมูลติวเตอร์ได้ กรุณาลองใหม่อีกครั้ง',
    validationError: 'กรุณาตรวจสอบตัวกรองที่มีข้อความแจ้งเตือน',
    noMatches: 'ไม่พบผลลัพธ์ที่ตรงกัน',
    noMatchesHint: 'ลองล้างตัวกรองบางรายการเพื่อดูคอร์สอื่นที่เปิดสอน',
    years: 'ปีประสบการณ์',
    newTutor: 'ติวเตอร์ใหม่',
    reviews: 'รีวิว',
    noFutureSlots: 'ยังไม่มีเวลาว่างในอนาคต',
    next: 'ครั้งถัดไป',
    hour: 'ชั่วโมง',
    viewTimes: 'ดูเวลาว่าง',
    cardNote:
      'แต่ละการ์ดแทนหนึ่งคอร์สที่ตรงกับตัวกรอง ราคาและวิชาจะไม่ถูกนำมาปะปนกับคอร์สอื่นของติวเตอร์คนเดียวกัน',
  },
} as const;

export type TutorSearchCopy = {
  [Key in keyof (typeof tutorSearchCopy)['en']]: string;
};
